print("===================[]")
print("KALKULATOR BY DILLON")
print("===================[]")
print("     STATISTIKA    ||")
print("x => MENCARI JML DATA ||")
print('r => MENCARI RATA"   ||')
print("k => segitiga      ||")
print("b => lingkaran     ||")
print('===================[]')
print('WALAUPUN BURIK TAPI WORKK=[]')
print('===================[]')